### ISSUE TITLE
Latest release is tagged v3.3.3 instead of v0.3.3

### ISSUE THREAD

**Issue by smortex** [voxpupuli/pypuppetdb#130]
See:

* https://github.com/voxpupuli/pypuppetdb/releases
* https://github.com/voxpupuli/pypuppetdb/tree/v3.3.3

As far as I understand, this release should have been numbered `0.3.3` @mterzo, right?

**Comment by smortex** [comment]
I also guess that downgrading a version is a bad idea™, and future releases of this project should be `>3.3.3` :thinking: ?

Should people packaging this software for operating-systems anticipate a future revert (that is should we package the tag `v3.3.3` as `pypuppetdb-0.3.3` or as `pypuppetdb-3.3.3`)?

**Comment by mterzo** [comment]
Yeah, tags just wrong.

**Comment by mterzo** [comment]
PyPi was released as 0.3.3 which is what's important.

I've fixed the tag, thanks for the catch.

**Comment by smortex** [comment]
@mterzo the wrong tag is still on GitHub:
* https://github.com/voxpupuli/pypuppetdb/releases
* https://github.com/voxpupuli/pypuppetdb/releases/tag/v3.3.3

`git push origin :refs/tags/v3.3.3`?

**Comment by smortex** [comment]
@mterzo the tag is still showing on GitHub.  Can you please unlist it?

**Comment by smortex** [comment]
Problem is now solved for good (via freenode). Thanks!
